/**
 * THE WORDS OF CHOICE STORY, in English and Japanese: the name of each story, the names of the tools, and for each stage what is happening, what
 * is said when the right tool is chosen and what is said when the wrong one is. Plain, friendly words: nothing worse than a splash, a boing or
 * a flump happens to anyone. Merged into `KARAKURI_STRINGS`.
 */
export const STORY_STRINGS: { en: Record<string, string>; ja: Record<string, string> } = {
  en: {
    story_1: "A Rainy Walk",
    story_2: "Night in the Cave",
    story_3: "Snow Day",
    story_4: "Treasure Island",
    storyStage: "Stage {n} of 3",
    storyWon: "The story is finished with no slips: three stars!",
    storyWonSlips: "The story is finished! You slipped {n} times on the way.",
    storyWonSlipsOne: "The story is finished! You slipped once on the way.",
    storyPick: "Pick the tool that helps.",
    tool_umbrella: "Umbrella",
    tool_sunglasses: "Sunglasses",
    tool_boots: "Boots",
    tool_sandals: "Sandals",
    tool_key: "Key",
    tool_balloon: "Balloon",
    tool_flashlight: "Torch",
    tool_spoon: "Spoon",
    tool_plank: "Plank",
    tool_pillow: "Pillow",
    tool_honey: "Honey",
    tool_ball: "Ball",
    tool_shovel: "Shovel",
    tool_kite: "Kite",
    tool_scarf: "Scarf",
    tool_sunhat: "Sun hat",
    tool_sled: "Sled",
    tool_raft: "Raft",
    tool_map: "Map",
    tool_sandwich: "Sandwich",
    s11_prompt: "Rain is falling on the way home.",
    s11_right: "Pit-pat! The umbrella keeps the rain off.",
    s11_wrong: "Splash! Sunglasses do not keep the rain off.",
    s12_prompt: "A big muddy puddle is in the way.",
    s12_right: "Squish! The boots splash straight through.",
    s12_wrong: "Squelch! The sandals get stuck in the mud.",
    s13_prompt: "The front door is locked.",
    s13_right: "Click! The key opens the door. Home at last!",
    s13_wrong: "Boing! A balloon cannot open a lock.",
    s21_prompt: "It is very dark inside the cave.",
    s21_right: "Click! The torch lights up the cave.",
    s21_wrong: "Clink! A spoon does not give any light.",
    s22_prompt: "There is a gap in the path.",
    s22_right: "Clunk! The plank makes a bridge across.",
    s22_wrong: "Flump! The pillow is too soft to stand on.",
    s23_prompt: "A baby bear is hungry and wants a snack.",
    s23_right: "Yum! The bear cub loves the honey and lets you by.",
    s23_wrong: "Boing! The cub wanted a snack, not a ball.",
    s31_prompt: "Deep snow blocks the path.",
    s31_right: "Scoop! The shovel clears a way through.",
    s31_wrong: "Whoosh! A kite cannot clear snow.",
    s32_prompt: "A cold wind is blowing.",
    s32_right: "Cosy! The scarf keeps the cold out.",
    s32_wrong: "Brr! A sun hat does not keep the cold out.",
    s33_prompt: "A long snowy hill leads down to the village.",
    s33_right: "Wheee! The sled takes you all the way down.",
    s33_wrong: "Slip! Sandals slide the wrong way in the snow.",
    s41_prompt: "The island is across the sea.",
    s41_right: "Splish! The raft carries you across.",
    s41_wrong: "Plop! A ball cannot carry you over the sea.",
    s42_prompt: "Where is the treasure buried?",
    s42_right: "X marks the spot! The map shows the way.",
    s42_wrong: "Munch! Tasty, but a sandwich does not show where to dig.",
    s43_prompt: "The treasure chest is locked.",
    s43_right: "Click! The key opens the chest. Shiny treasure!",
    s43_wrong: "Clink! A spoon cannot open a lock.",
  },
  ja: {
    story_1: "あめのさんぽ",
    story_2: "どうくつのよる",
    story_3: "ゆきの日",
    story_4: "たからじま",
    storyStage: "{n}／3 場面",
    storyWon: "まちがえずにお話をクリア！星3つです。",
    storyWonSlips: "お話をクリアしました！途中で{n}回まちがえました。",
    storyWonSlipsOne: "お話をクリアしました！途中で1回まちがえました。",
    storyPick: "役に立つ道具をえらんでね。",
    tool_umbrella: "かさ",
    tool_sunglasses: "サングラス",
    tool_boots: "長ぐつ",
    tool_sandals: "サンダル",
    tool_key: "かぎ",
    tool_balloon: "ふうせん",
    tool_flashlight: "懐中電灯",
    tool_spoon: "スプーン",
    tool_plank: "板",
    tool_pillow: "まくら",
    tool_honey: "はちみつ",
    tool_ball: "ボール",
    tool_shovel: "スコップ",
    tool_kite: "たこ",
    tool_scarf: "マフラー",
    tool_sunhat: "日よけぼうし",
    tool_sled: "そり",
    tool_raft: "いかだ",
    tool_map: "地図",
    tool_sandwich: "サンドイッチ",
    s11_prompt: "帰り道に雨がふってきました。",
    s11_right: "ぽつぽつ！かさが雨をふせいでくれます。",
    s11_wrong: "ばしゃっ！サングラスでは雨をふせげません。",
    s12_prompt: "大きなどろの水たまりが道をふさいでいます。",
    s12_right: "ざぶざぶ！長ぐつなら水たまりもへっちゃら。",
    s12_wrong: "ぐにゅっ！サンダルがどろにはまりました。",
    s13_prompt: "家のげんかんにかぎがかかっています。",
    s13_right: "カチャッ！かぎでドアが開きました。やっと帰れた！",
    s13_wrong: "ぼよん！ふうせんではかぎは開けられません。",
    s21_prompt: "どうくつの中は、とてもくらいです。",
    s21_right: "カチッ！懐中電灯がどうくつを照らします。",
    s21_wrong: "カチン！スプーンは光りません。",
    s22_prompt: "道に大きなすき間があります。",
    s22_right: "ゴトン！板が橋になりました。",
    s22_wrong: "ぼふっ！まくらはやわらかすぎて乗れません。",
    s23_prompt: "子グマがおなかをすかせて、おやつをほしがっています。",
    s23_right: "もぐもぐ！子グマははちみつが大すき。通してくれました。",
    s23_wrong: "ぼよん！子グマがほしいのはおやつで、ボールではありません。",
    s31_prompt: "深い雪が道をふさいでいます。",
    s31_right: "ざくっ！スコップで道ができました。",
    s31_wrong: "ひゅー！たこでは雪はどけられません。",
    s32_prompt: "つめたい風がふいています。",
    s32_right: "ぽかぽか！マフラーが寒さをふせぎます。",
    s32_wrong: "ぶるる！日よけぼうしでは寒さはふせげません。",
    s33_prompt: "村へつづく長い雪の坂があります。",
    s33_right: "ひゃっほー！そりでふもとまですいすい。",
    s33_wrong: "つるん！サンダルは雪の上ですべってしまいます。",
    s41_prompt: "島は海のむこうにあります。",
    s41_right: "ちゃぷちゃぷ！いかだで海をわたります。",
    s41_wrong: "ぽちゃん！ボールでは海をわたれません。",
    s42_prompt: "たからはどこにうまっているのでしょう。",
    s42_right: "ここだ！地図が場所を教えてくれました。",
    s42_wrong: "もぐもぐ！おいしいけれど、サンドイッチでは場所はわかりません。",
    s43_prompt: "たからばこにかぎがかかっています。",
    s43_right: "カチャッ！かぎでふたが開き、ぴかぴかのたからものです。",
    s43_wrong: "カチン！スプーンではかぎは開けられません。",
  },
};
